package insights

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
)

// denyQuerier is the minimum shape gatherGovernanceDenies needs. Both
// *pgxpool.Pool and test fakes satisfy it, allowing query-error paths
// to be exercised without a live Postgres.
type denyQuerier interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
}

// dispatchCLIEnvVar toggles which transport callLLM uses. When unset or
// anything other than "true", insights are generated by shelling out to
// the octi CLI (free). When "true", the HTTP API path to Ollama Cloud
// (OpenAI-compatible chat-completions) is used. The API path replaced
// the legacy Anthropic path in slice 2 to bring LLM cost under the
// operator's existing flat $20/mo Ollama Cloud Pro subscription rather
// than pay-per-token Anthropic billing.
const dispatchCLIEnvVar = "SENTINEL_INSIGHTS_USE_API"

// defaultOllamaModel is the Ollama Cloud model used for insight
// summarization when no override is supplied. glm-5.1:cloud is cheap
// and strong enough for structured summary / severity tagging tasks.
const defaultOllamaModel = "glm-5.1:cloud"

// octiDispatchResponse mirrors the contract of the octi MCP tool
// `dispatch_prompt_to_cli`. Slice 1 owns the tool; this slice only
// consumes its JSON output.
type octiDispatchResponse struct {
	DriverUsed string `json:"driver_used"`
	Output     string `json:"output"`
	DurationMS int    `json:"duration_ms"`
	Error      string `json:"error,omitempty"`
}

// Generator orchestrates insight generation from health scores and telemetry.
type Generator struct {
	pool       *pgxpool.Pool
	redis      *redis.Client
	apiURL     string
	apiKey     string
	model      string
	store      *Store
	maxFreq    time.Duration
	lastGenAt  time.Time
	scoreDelta int     // threshold for score delta to trigger generation
	volumeSpike float64 // multiplier for volume spike detection
	httpClient *http.Client
}

// GeneratorConfig holds config for the generator.
type GeneratorConfig struct {
	APIKey               string
	Model                string
	MaxFrequencyMinutes  int
	ScoreDeltaThreshold  int
	VolumeSpikeThreshold float64
	NtfyTopic            string
}

// NewGenerator constructs a Generator.
func NewGenerator(pool *pgxpool.Pool, redisClient *redis.Client, cfg GeneratorConfig) *Generator {
	maxFreq := time.Duration(cfg.MaxFrequencyMinutes) * time.Minute
	if maxFreq == 0 {
		maxFreq = 60 * time.Minute
	}
	scoreDelta := cfg.ScoreDeltaThreshold
	if scoreDelta == 0 {
		scoreDelta = 5
	}
	volumeSpike := cfg.VolumeSpikeThreshold
	if volumeSpike == 0 {
		volumeSpike = 3.0
	}
	model := cfg.Model
	if model == "" {
		model = defaultOllamaModel
	}

	return &Generator{
		pool:        pool,
		redis:       redisClient,
		apiURL:      "https://ollama.com",
		apiKey:      cfg.APIKey,
		model:       model,
		store:       NewStore(pool, redisClient, cfg.NtfyTopic),
		maxFreq:     maxFreq,
		scoreDelta:  scoreDelta,
		volumeSpike: volumeSpike,
		httpClient:  &http.Client{Timeout: 60 * time.Second},
	}
}

// MaybeGenerate checks for signals and generates insights if warranted.
func (g *Generator) MaybeGenerate(ctx context.Context) ([]Insight, error) {
	// Rate cap check.
	if !g.lastGenAt.IsZero() && time.Since(g.lastGenAt) < g.maxFreq {
		return nil, nil
	}

	// Gather inputs.
	inputs, err := g.gatherInputs(ctx)
	if err != nil {
		return nil, fmt.Errorf("gather inputs: %w", err)
	}

	// Determine which categories have signal.
	categories := g.detectSignals(inputs)
	if len(categories) == 0 {
		return nil, nil
	}

	var allInsights []Insight

	for _, cat := range categories {
		insights, err := g.generateCategory(ctx, cat, inputs)
		if err != nil {
			log.Printf("insights: %s generation failed: %v", cat, err)
			continue
		}
		allInsights = append(allInsights, insights...)
	}

	if len(allInsights) == 0 {
		return nil, nil
	}

	// Store.
	if err := g.store.Write(ctx, allInsights); err != nil {
		return nil, fmt.Errorf("store insights: %w", err)
	}

	g.lastGenAt = time.Now()
	return allInsights, nil
}

// gatherInputs collects data from Neon and Redis.
func (g *Generator) gatherInputs(ctx context.Context) (*GeneratorInputs, error) {
	inputs := &GeneratorInputs{
		FailureCounts:  make(map[string]int),
		PlatformStats:  make(map[string]int),
		DispatchCounts: make(map[string]int),
		BudgetPcts:     make(map[string]int),
	}

	// Health score deltas: compare latest vs prior.
	rows, err := g.pool.Query(ctx, `
		WITH latest AS (
			SELECT scope_type, scope_value, score, dimensions,
			       ROW_NUMBER() OVER (PARTITION BY scope_type, scope_value ORDER BY timestamp DESC) as rn
			FROM health_scores
		)
		SELECT l1.scope_type, l1.scope_value, l1.score, COALESCE(l2.score, l1.score), l1.dimensions
		FROM latest l1
		LEFT JOIN latest l2 ON l1.scope_type = l2.scope_type AND l1.scope_value = l2.scope_value AND l2.rn = 2
		WHERE l1.rn = 1
	`)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var d HealthScoreDelta
			var dimsJSON []byte
			if err := rows.Scan(&d.ScopeType, &d.ScopeValue, &d.Score, &d.Prior, &dimsJSON); err == nil {
				d.Delta = d.Score - d.Prior
				if dimsJSON != nil {
					_ = json.Unmarshal(dimsJSON, &d.Dimensions)
				}
				inputs.ScoreDeltas = append(inputs.ScoreDeltas, d)
			}
		}
	}

	// Failure counts by repo (24h).
	fRows, err := g.pool.Query(ctx, `
		SELECT COALESCE(repository, 'unknown'), COUNT(*)::int
		FROM execution_events
		WHERE timestamp >= NOW() - INTERVAL '24 hours'
		  AND (has_error OR (exit_code IS NOT NULL AND exit_code != 0))
		GROUP BY repository
		ORDER BY COUNT(*) DESC
		LIMIT 20
	`)
	if err == nil {
		defer fRows.Close()
		for fRows.Next() {
			var repo string
			var count int
			if fRows.Scan(&repo, &count) == nil {
				inputs.FailureCounts[repo] = count
			}
		}
	}

	// Platform failure stats (24h).
	pRows, err := g.pool.Query(ctx, `
		SELECT COALESCE(agent_id, 'unknown'), COUNT(*)::int
		FROM execution_events
		WHERE timestamp >= NOW() - INTERVAL '24 hours'
		  AND (has_error OR (exit_code IS NOT NULL AND exit_code != 0))
		GROUP BY agent_id
	`)
	if err == nil {
		defer pRows.Close()
		for pRows.Next() {
			var platform string
			var count int
			if pRows.Scan(&platform, &count) == nil {
				inputs.PlatformStats[platform] = count
			}
		}
	}

	// Event volume (24h).
	g.pool.QueryRow(ctx, `
		SELECT COUNT(*)::int FROM execution_events
		WHERE timestamp >= NOW() - INTERVAL '24 hours'
	`).Scan(&inputs.EventVolume)

	// Governance deny counts (24h) grouped by metadata->>'reason'. This is
	// the signal side of slice 2: policies deny things, but until we
	// aggregate the reasons we can't surface emerging patterns. A spike
	// in any single reason is a candidate for a governance insight.
	denies, govErr := gatherGovernanceDenies(ctx, g.pool)
	if govErr != nil {
		// Log-and-continue: missing table during migration or transient DB
		// error should not wipe out the rest of the insight cycle, but a
		// silent swallow loses the signal entirely. Surface via log so
		// operators at least see the failure in stderr.
		log.Printf("insights: gatherGovernanceDenies failed: %v", govErr)
	}
	inputs.GovernanceDenyCounts = denies

	// Redis state.
	if g.redis != nil {
		if skipList, err := g.redis.HGetAll(ctx, "octi:skip-list").Result(); err == nil {
			inputs.SkipListSize = len(skipList)
		}
		for _, platform := range []string{"claude", "copilot", "gemini", "codex"} {
			if count, err := g.redis.Get(ctx, "octi:dispatch-count:"+platform).Int(); err == nil {
				inputs.DispatchCounts[platform] = count
			}
			if capStr, err := g.redis.HGet(ctx, "octi:budget:"+platform, "daily_cap").Result(); err == nil {
				cap := 0
				fmt.Sscanf(capStr, "%d", &cap)
				if cap > 0 {
					dispatches := inputs.DispatchCounts[platform]
					inputs.BudgetPcts[platform] = (dispatches * 100) / cap
				}
			}
		}
	}

	return inputs, nil
}

// detectSignals determines which insight categories have enough signal.
func (g *Generator) detectSignals(inputs *GeneratorInputs) []InsightCategory {
	var cats []InsightCategory

	// Health: any score moved > threshold.
	for _, d := range inputs.ScoreDeltas {
		if d.Delta > g.scoreDelta || d.Delta < -g.scoreDelta {
			cats = append(cats, CategoryHealth)
			break
		}
	}

	// Pattern: failures exist. Governance: any deny_reason has spiked
	// above 10 in the last 24h. These are SEPARATE categories so the
	// governance-specific briefing always fires on a deny spike, even
	// when execution failures are also present (the common case). The
	// prior single-category design merged governance into the generic
	// failure briefing whenever failures > 0, defeating the purpose of
	// a dedicated governance prompt.
	totalFailures := 0
	for _, c := range inputs.FailureCounts {
		totalFailures += c
	}
	if totalFailures > 0 {
		cats = append(cats, CategoryPattern)
	}
	for _, c := range inputs.GovernanceDenyCounts {
		if c > 10 {
			cats = append(cats, CategoryGovernance)
			break
		}
	}

	// Recommendation: any platform has data.
	if len(inputs.DispatchCounts) > 0 {
		cats = append(cats, CategoryRecommendation)
	}

	// Anomaly: volume spike — compare to 7d average.
	// Simple heuristic: if event volume > 0, always include for first run.
	// In practice, compare against historical average.
	if inputs.EventVolume > 100 {
		cats = append(cats, CategoryAnomaly)
	}

	return cats
}

// generateCategory calls the LLM for a single insight category.
func (g *Generator) generateCategory(ctx context.Context, cat InsightCategory, inputs *GeneratorInputs) ([]Insight, error) {
	var systemPrompt, userPrompt string

	switch cat {
	case CategoryHealth:
		systemPrompt = healthNarrativeSystemPrompt()
		userPrompt = buildHealthPrompt(inputs.ScoreDeltas, inputs.FailureCounts)
	case CategoryPattern:
		systemPrompt = patternDetectionSystemPrompt()
		userPrompt = buildPatternPrompt(inputs.FailureCounts, inputs.PlatformStats)
	case CategoryGovernance:
		// Dedicated governance briefing — always fires on a deny spike,
		// independent of whether execution failures are also present.
		systemPrompt = governancePatternSystemPrompt()
		userPrompt = buildGovernancePrompt(inputs.GovernanceDenyCounts)
	case CategoryRecommendation:
		systemPrompt = dispatchRecommendationSystemPrompt()
		userPrompt = buildRecommendationPrompt(inputs.DispatchCounts, inputs.BudgetPcts, inputs.PlatformStats)
	case CategoryAnomaly:
		systemPrompt = anomalyAlertSystemPrompt()
		userPrompt = buildAnomalyPrompt(inputs.EventVolume, float64(inputs.EventVolume))
	default:
		return nil, fmt.Errorf("unknown category: %s", cat)
	}

	raw, err := g.callLLM(ctx, systemPrompt, userPrompt)
	if err != nil {
		return nil, err
	}

	var llmResults []llmInsight
	if err := json.Unmarshal([]byte(raw), &llmResults); err != nil {
		return nil, fmt.Errorf("parse LLM response: %w", err)
	}

	now := time.Now().UTC()
	insights := make([]Insight, 0, len(llmResults))
	for i, r := range llmResults {
		ins := Insight{
			ID:              fmt.Sprintf("ins-%s-%d-%d", cat, now.Unix(), i),
			Timestamp:       now,
			Category:        InsightCategory(r.Category),
			Severity:        InsightSeverity(r.Severity),
			Narrative:       r.Narrative,
			Evidence:        r.Evidence,
			SuggestedAction: r.SuggestedAction,
			ScopeType:       r.ScopeType,
			ScopeValue:      r.ScopeValue,
		}
		// Validate severity.
		switch ins.Severity {
		case SeverityInfo, SeverityWarning, SeverityHigh, SeverityCritical:
			// valid
		default:
			ins.Severity = SeverityInfo
		}
		insights = append(insights, ins)
	}

	return insights, nil
}

// callLLM routes the prompt to either the octi CLI dispatch bridge
// (default, free) or the Ollama Cloud HTTPS API (paid, but under the
// operator's flat $20/mo Ollama Cloud Pro subscription — no per-token
// billing). Selection is controlled by SENTINEL_INSIGHTS_USE_API=true.
func (g *Generator) callLLM(ctx context.Context, systemPrompt, userPrompt string) (string, error) {
	if strings.EqualFold(os.Getenv(dispatchCLIEnvVar), "true") {
		return g.callLLMViaAPI(ctx, systemPrompt, userPrompt)
	}
	return g.dispatchPromptToCLI(ctx, systemPrompt, userPrompt)
}

// dispatchPromptToCLI shells out to `octi mcp-call dispatch_prompt_to_cli`
// which slice 1 provides. The tool picks a local CLI driver (copilot,
// codex, claude-code) and returns a JSON envelope with the raw output.
// We pass the system + user prompts as flags and parse the envelope.
//
// If the MCP tool is not yet implemented (slice 1 pending) this will
// fail loudly — callers see the exec error and the insight pipeline
// logs it via generateCategory's error path. No silent drops.
func (g *Generator) dispatchPromptToCLI(ctx context.Context, systemPrompt, userPrompt string) (string, error) {
	// Use the mcp-call CLI shape — portable across shells and doesn't
	// require us to ship an HTTP client for the pulpo bridge. If the
	// bridge is preferred later we can swap just this function.
	args := []string{
		"mcp-call", "dispatch_prompt_to_cli",
		"--prompt", userPrompt,
		"--system-prompt", systemPrompt,
		"--timeout-seconds", "60",
	}
	cmd := exec.CommandContext(ctx, "octi", args...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("octi dispatch: %w (stderr: %s)", err, strings.TrimSpace(stderr.String()))
	}

	var resp octiDispatchResponse
	if err := json.Unmarshal(stdout.Bytes(), &resp); err != nil {
		// Some CLI shapes return raw text; surface as best-effort.
		return strings.TrimSpace(stdout.String()), nil
	}
	if resp.Error != "" {
		return "", fmt.Errorf("octi dispatch error (driver=%s): %s", resp.DriverUsed, resp.Error)
	}
	return resp.Output, nil
}

// callLLMViaAPI sends a prompt to the Ollama Cloud chat-completions API
// (OpenAI-compatible). Request/response shapes match the OpenAI
// ChatCompletion contract that Ollama Cloud exposes at /v1.
func (g *Generator) callLLMViaAPI(ctx context.Context, systemPrompt, userPrompt string) (string, error) {
	type chatMessage struct {
		Role    string `json:"role"`
		Content string `json:"content"`
	}
	type chatCompletionRequest struct {
		Model     string        `json:"model"`
		Messages  []chatMessage `json:"messages"`
		MaxTokens int           `json:"max_tokens,omitempty"`
	}
	type chatCompletionResponse struct {
		Choices []struct {
			Message chatMessage `json:"message"`
		} `json:"choices"`
		Error *struct {
			Message string `json:"message"`
			Type    string `json:"type"`
		} `json:"error,omitempty"`
	}

	reqBody := chatCompletionRequest{
		Model: g.model,
		Messages: []chatMessage{
			{Role: "system", Content: systemPrompt},
			{Role: "user", Content: userPrompt},
		},
		MaxTokens: 1024,
	}

	data, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}

	endpoint := strings.TrimRight(g.apiURL, "/") + "/v1/chat/completions"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(data))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+g.apiKey)

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("http request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("API returned status %d", resp.StatusCode)
	}

	var apiResp chatCompletionResponse
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return "", fmt.Errorf("decode response: %w", err)
	}
	if apiResp.Error != nil {
		return "", fmt.Errorf("API error: %s", apiResp.Error.Message)
	}
	for _, ch := range apiResp.Choices {
		if ch.Message.Content != "" {
			return ch.Message.Content, nil
		}
	}
	return "", fmt.Errorf("no content in response")
}

// gatherGovernanceDenies returns deny counts grouped by reason over the
// last 24h. Accepts anything satisfying denyQuerier so the production
// pool and test fakes both work. Returns an error on query or iteration
// failure so the caller can log (rather than silently swallowing the
// signal loss during migrations or DB outages).
func gatherGovernanceDenies(ctx context.Context, q denyQuerier) (map[string]int, error) {
	out := make(map[string]int)
	if q == nil {
		return out, nil
	}
	rows, err := q.Query(ctx, `
		SELECT COALESCE(NULLIF(metadata->>'reason', ''), 'unspecified') AS reason,
		       COUNT(*)::int
		FROM governance_events
		WHERE timestamp >= NOW() - INTERVAL '24 hours'
		  AND outcome = 'deny'
		GROUP BY reason
		ORDER BY COUNT(*) DESC
		LIMIT 50
	`)
	if err != nil {
		return out, fmt.Errorf("query governance_events: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var reason string
		var count int
		if err := rows.Scan(&reason, &count); err != nil {
			log.Printf("insights: governance deny scan error: %v", err)
			continue
		}
		out[reason] = count
	}
	if err := rows.Err(); err != nil {
		return out, fmt.Errorf("iterate governance_events: %w", err)
	}
	return out, nil
}
