package router

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os/exec"
	"strings"
	"text/template"
	"time"

	"github.com/AgentGuardHQ/sentinel/internal/analyzer"
)

// GhClient implements GitHubClient using the gh CLI binary.
type GhClient struct {
	repo   string
	labels []string
}

// NewGhClient returns a GhClient targeting the given repo (owner/name).
func NewGhClient(repo string, labels []string) *GhClient {
	return &GhClient{repo: repo, labels: labels}
}

// SearchIssues runs `gh search issues` and returns matching issue titles.
// Returns an empty slice (not an error) when no issues match.
func (g *GhClient) SearchIssues(ctx context.Context, query string) ([]string, error) {
	args := []string{
		"search", "issues",
		"--repo", g.repo,
		"--state", "open",
		"--match", "title",
		"--json", "title",
		"--limit", "5",
		query,
	}

	out, err := exec.CommandContext(ctx, "gh", args...).Output()
	if err != nil {
		// gh exits non-zero when no results are found in some versions; treat as empty.
		if len(out) == 0 {
			return nil, nil
		}
		// Attempt to parse what we got before surfacing the error.
	}

	var results []struct {
		Title string `json:"title"`
	}
	if jsonErr := json.Unmarshal(out, &results); jsonErr != nil {
		if err != nil {
			return nil, fmt.Errorf("gh search failed (%w) and output could not be parsed: %v", err, jsonErr)
		}
		return nil, nil
	}

	titles := make([]string, len(results))
	for i, r := range results {
		titles[i] = r.Title
	}
	return titles, nil
}

// CreateIssue formats and creates a GitHub issue, returning the URL.
func (g *GhClient) CreateIssue(
	ctx context.Context,
	finding analyzer.InterpretedFinding,
	repo string,
	labels []string,
) (string, error) {
	title, body := FormatIssue(finding)

	args := []string{
		"issue", "create",
		"--repo", repo,
		"--title", title,
		"--body", body,
	}
	for _, l := range labels {
		args = append(args, "--label", l)
	}

	out, err := exec.CommandContext(ctx, "gh", args...).Output()
	if err != nil {
		return "", fmt.Errorf("gh issue create: %w", err)
	}

	// gh prints the issue URL as the last line.
	url := strings.TrimSpace(string(out))
	if lines := strings.Split(url, "\n"); len(lines) > 0 {
		url = strings.TrimSpace(lines[len(lines)-1])
	}
	return url, nil
}

// issueBodyTmpl is the raw template source.  Funcs (mul, now) are registered
// at call time in FormatIssue so the package-level parse doesn't need them.
const issueBodyTmpl = `## Summary

**Policy:** {{ .Finding.PolicyID }}
**Pass:** {{ .Finding.Pass }}
**Confidence:** {{ printf "%.0f%%" (mul .Confidence 100.0) }}
**Novelty:** {{ .Novelty }}
**Detected At:** {{ .Finding.DetectedAt.Format "2006-01-02 15:04 UTC" }}

## Metrics

| Metric | Value |
|--------|-------|
| Count | {{ .Finding.Metrics.Count }} |
| Rate | {{ printf "%.1f%%" (mul .Finding.Metrics.Rate 100.0) }} |
| Baseline Rate | {{ printf "%.1f%%" (mul .Finding.Metrics.BaselineRate 100.0) }} |
| Deviation | {{ printf "%.1fσ" .Finding.Metrics.Deviation }} |
| Sample Size | {{ .Finding.Metrics.SampleSize }} |

## Reasoning

{{ .Reasoning }}

## Recommended Remediation

{{ if .Remediation }}{{ .Remediation }}{{ else }}_No specific remediation suggested._{{ end }}
{{ if .PastFindings }}
## Related Past Findings

{{ range .PastFindings }}- {{ . }}
{{ end }}{{ end }}
---
_Generated by [Sentinel](https://github.com/AgentGuardHQ/sentinel) on {{ now }}_
`

// FormatIssue returns the title and markdown body for a GitHub issue.
// Exported so github_test.go can call it directly.
func FormatIssue(finding analyzer.InterpretedFinding) (title, body string) {
	title = fmt.Sprintf("[Sentinel] %s", finding.SuggestedTitle)

	funcMap := template.FuncMap{
		"mul": func(a, b float64) float64 { return a * b },
		"now": func() string { return time.Now().UTC().Format("2006-01-02 15:04 UTC") },
	}

	tmpl, err := template.New("issue").Funcs(funcMap).Parse(issueBodyTmpl)
	if err != nil {
		body = fmt.Sprintf("Policy: %s | Pass: %s | Confidence: %.2f\n\n%s",
			finding.Finding.PolicyID, finding.Finding.Pass, finding.Confidence, finding.Reasoning)
		return title, body
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, finding); err != nil {
		body = fmt.Sprintf("Policy: %s | Pass: %s | Confidence: %.2f\n\n%s",
			finding.Finding.PolicyID, finding.Finding.Pass, finding.Confidence, finding.Reasoning)
		return title, body
	}

	return title, buf.String()
}
